/** Explicit equivalent configurations of the pinned runtime. */
export type FixtureProfile =
  | "multi-session" | "multi-session-limited"
  | "two-factor-lockout-fractional" | "two-factor-lockout-zero" | "two-factor-lockout-disabled" | "two-factor-skip-verification"
  | "two-factor-totp-default" | "two-factor-totp-config" | "two-factor-totp-disabled" | "two-factor-totp-zero"
  | "session-fields" | "session-fields-plugins"
  | "device-custom" | "device-configured" | "device-unicode" | "device-too-long"
  | "siwe" | "siwe-email" | "siwe-contract"
  | "phone-default" | "phone-signup" | "phone-proof" | "phone-custom"
  | "session-deferred"
  | "session-no-refresh"
  | "session-deferred-no-refresh"
  | "session-no-freshness"
  | "session-cookie-cleanup"
  | "magic-link-hashed"
  | "magic-link-disabled"
  | "passwordless-hashed"
  | "passwordless-encrypted-reuse"
  | "passwordless-proof"
  | "passwordless-proof-explicit"
  | "passwordless-disabled"
  | "verification-cleanup"
  | "verification-no-cleanup"
  | "email-verification-required"
  | "email-verification-no-signup-mail"
  | "email-verification-failing-notifications"
  | "ott-default"
  | "ott-hashed"
  | "ott-no-cookie"
  | "ott-server-header"
  | "ott-refresh-disabled"
  | "ott-refresh-deferred"
  | "jwt-default" | "jwt-es256" | "jwt-es512" | "jwt-rs256" | "jwt-ps256"
  | "jwt-session-normal" | "jwt-session-disabled" | "jwt-session-deferred"
  | "jwt-claims" | "jwt-path-header" | "jwt-plain-rotation"
  | "org-teams-dynamic"
  | "org-roles-limited"
  | "org-roles-no-ac"
  | "org-roles-delegated"
  | "org-roles-callback"
  | "org-teams"
  | "org-teams-no-default"
  | "org-teams-limited"
  | "org-teams-removable";

export function authProfilePath(profile: FixtureProfile): string {
  return `/__test/profiles/${profile}/api/auth`;
}
