/** Explicit equivalent configurations of the pinned runtime. */
export type FixtureProfile =
  | "org-creation-denied" | "org-creation-limit" | "org-creation-negative" | "org-creation-infinity" | "org-creation-nan" | "org-creation-callback" | "org-creation-founder" | "org-creation-empty-role" | "admin-duration-hook-error" | "admin-duration-zero" | "admin-duration-fractional" | "admin-duration-negative" | "admin-duration-invalid" | "admin-duration-nan" | "admin-role-manager" | "admin-role-creator" | "admin-standard" | "admin-deny-all" | "admin-exact-role" | "admin-empty-role" | "org-creation-hooks" | "org-creation-hooks-no-team" | "org-creation-hooks-denied" | "two-factor-trust-fractional" | "two-factor-trust-zero-challenge" | "two-factor-trust-negative-challenge" | "two-factor-trust-zero" | "two-factor-trust-negative" | "two-factor-trust-cleanup-disabled" | "admin-banned-message" | "admin-banned-message-error" | "api-key-hooks"
  | "multi-session" | "multi-session-limited"
  | "two-factor-backup-plain" | "two-factor-backup-zero" | "two-factor-backup-negative" | "two-factor-backup-encrypted" | "two-factor-backup-custom" | "two-factor-backup-invalid-length"
  | "two-factor-otp-zero" | "two-factor-otp-negative" | "two-factor-otp-plain" | "two-factor-otp-hashed" | "two-factor-otp-encrypted" | "two-factor-otp-custom-hash" | "two-factor-otp-custom-cipher"
  | "two-factor-pending-session-cancel" | "two-factor-pending-session-forbidden"
  | "two-factor-skip-session-cancel" | "two-factor-skip-session-forbidden"
  | "two-factor-skip-user-hook"
  | "two-factor-passwordless" | "two-factor-passwordless-child-required" | "two-factor-passwordless-child-optional"
  | "two-factor-lockout-fractional" | "two-factor-lockout-zero" | "two-factor-lockout-disabled" | "two-factor-skip-verification"
  | "two-factor-totp-default" | "two-factor-totp-config" | "two-factor-totp-disabled" | "two-factor-totp-zero"
  | "session-fields" | "session-fields-plugins"
  | "api-key-generation" | "passkey-fresh" | "passkey-no-freshness"
  | "device-custom" | "device-configured" | "device-unicode" | "device-too-long"
  | "siwe" | "siwe-email" | "siwe-contract"
  | "phone-default" | "phone-signup" | "phone-proof" | "phone-custom"
  | "openapi-default" | "openapi-configured" | "openapi-disabled" | "openapi-jwt" | "openapi-username" | "openapi-custom-schema" | "openapi-plugins" | "openapi-plugins-teams" | "openapi-plugins-configured"
  | "session-deferred"
  | "session-no-refresh"
  | "session-deferred-no-refresh"
  | "session-no-freshness"
  | "session-cookie-cleanup"
  | "magic-link-hashed"
  | "magic-link-disabled"
  | "passwordless-hashed"
  | "passwordless-encrypted-reuse"
  | "passwordless-proof"
  | "passwordless-proof-explicit"
  | "passwordless-disabled"
  | "verification-cleanup"
  | "verification-no-cleanup"
  | "email-verification-required"
  | "email-verification-no-signup-mail"
  | "email-verification-failing-notifications"
  | "ott-default"
  | "ott-hashed"
  | "ott-no-cookie"
  | "ott-server-header"
  | "ott-refresh-disabled"
  | "ott-refresh-deferred"
  | "jwt-default" | "jwt-es256" | "jwt-es512" | "jwt-rs256" | "jwt-ps256"
  | "jwt-session-normal" | "jwt-session-disabled" | "jwt-session-deferred"
  | "jwt-claims" | "jwt-path-header" | "jwt-plain-rotation"
  | "org-teams-dynamic"
  | "org-roles-limited"
  | "org-roles-no-ac"
  | "org-roles-delegated"
  | "org-roles-callback"
  | "org-deletion-disabled"
  | "org-deletion-hooks"
  | "org-deletion-hooks-disabled"
  | "org-teams"
  | "org-teams-no-default"
  | "org-teams-limited"
  | "org-teams-removable";

export function authProfilePath(profile: FixtureProfile): string {
  return `/__test/profiles/${profile}/api/auth`;
}
