import {betterAuth} from 'better-auth';
import {APIError,isAPIError,createAuthEndpoint,createAuthMiddleware} from 'better-auth/api';
import {Database} from 'bun:sqlite';
import {getMigrations} from 'better-auth/db/migration';
const db=new Database(':memory:');let events:any[]=[];let cookieB='';
const authOptions={database:db,baseURL:'http://original.test',secret:'close181-real-composition-secret-32',logger:{disabled:true},emailAndPassword:{enabled:true},disabledPaths:['/disabled'],databaseHooks:{user:{update:{before(data,c){events.push({stage:'db-before',principal:c?.context.session?.user.id??null,physical:new URL(c!.request!.url).pathname,url:c!.request!.url,authority:!!(c!.request as any).trustedPrincipal,logical:c!.body});return {data}},after(user){events.push({stage:'db-after',principal:user.id})}}}},hooks:{before:createAuthMiddleware(async c=>{if(!c.headers?.has('x-mode'))return;events.push({stage:'global-before',body:c.body,physical:new URL(c.request!.url).pathname});const mode=c.headers.get('x-mode');if(mode==='stop')return c.json({stopped:true});if(mode==='no-patch')return;if(mode==='context-request')return {context:{path:'/logical-patched',request:new Request('http://patched.test/physical',{method:'POST',headers:{cookie:cookieB},body:'physical'}),body:{name:'patched'}}};return {context:{body:{name:'patched'},headers:new Headers({'x-winner':'global','x-global-input':'yes'})}}}),after:createAuthMiddleware(async c=>{if(!c.headers?.has('x-mode'))return;events.push({stage:'global-match-after',error:isAPIError(c.context.returned)});events.push({stage:'global-after',path:c.path,body:c.body,winner:c.headers.get('x-winner'),error:isAPIError(c.context.returned)});const mode=c.headers.get('x-mode');if(mode==='after-ordinary')throw new Error('private after cause');if(mode==='after-api')throw c.error('FORBIDDEN',{message:'after explicit'});c.setHeader('x-global','after')})},plugins:[{
 id:'physical-first',init(c){return {context:{marker:'first'}}},async onRequest(r,c){const mode=r.headers.get('x-mode');if(!mode)return;events.push({stage:'http-first',path:new URL(r.url).pathname,base:c.options.baseURL,authority:!!(r as any).trustedPrincipal});if(mode==='early')return {response:Response.json({early:true})};if(mode==='request-ordinary')throw new Error('request ordinary');if(mode==='request-api')throw new APIError('FORBIDDEN',{message:'request explicit'});if(mode==='replace'){const current=await auth.api.getSession({headers:new Headers({cookie:r.headers.get('cookie')!})});(r as any).trustedPrincipal=current!.user.id;const headers=new Headers(r.headers);headers.set('cookie',cookieB);return {request:new Request('http://replacement.test/api/auth/write',{method:'POST',headers,body:JSON.stringify({name:'original-replace'})})}}},onResponse(r,c){const mode=r.headers.get('x-mode');if(!mode && r.headers.get('x-routed-mode')===null){/* supplied mode below is physical onResponse context absent, use activeMode */}if(!activeMode)return;events.push({stage:'http-response-first',status:r.status,global:r.headers.get('x-global'),base:c.options.baseURL,cors:r.headers.get('access-control-allow-origin')});if(activeMode==='response-ordinary')throw new Error('response ordinary');if(activeMode==='response-api')throw new APIError('FORBIDDEN',{message:'response explicit'});if(activeMode==='response-replace')return {response:new Response('replacement',{status:202,headers:{'x-replaced-response':'yes','content-type':'text/plain'}})}}}, {
 id:'physical-second',init(c){if(c.marker!=='first')throw new Error('init order');return {context:{marker:'second'}}},onRequest(r,c){if(r.headers.has('x-mode'))events.push({stage:'http-second',path:new URL(r.url).pathname,authority:!!(r as any).trustedPrincipal,base:c.options.baseURL})},hooks:{before:[{matcher:c=>c.headers?.has('x-mode')??false,handler:createAuthMiddleware(async c=>{events.push({stage:'plugin-before',body:c.body,winner:c.headers?.get('x-winner')});const headers=new Headers(c.headers);headers.set('x-winner','plugin');return {context:{headers}}})}],after:[{matcher:c=>c.headers?.has('x-mode')??false,handler:createAuthMiddleware(async c=>{events.push({stage:'plugin-after',path:c.path,status:(c.context.returned as any)?.statusCode??200,body:c.body,winner:c.headers?.get('x-winner')})})}]},endpoints:{write:createAuthEndpoint('/write',{method:'POST',cloneRequest:true},async c=>{const current=await auth.api.getSession({headers:new Headers({cookie:c.headers!.get('cookie')!})});c.context.session=current;events.push({stage:'handler',path:c.path,principal:current!.user.id,body:c.body,winner:c.headers!.get('x-winner'),setting:c.context.marker});if((c.request as any).trustedPrincipal)throw new Error('inherited wrong principal');await c.context.internalAdapter.updateUser(current!.user.id,{name:c.body.name});c.setCookie('issued','yes',{path:'/'});const mode=c.headers!.get('x-mode');if(mode==='handler-ordinary')throw new Error('handler ordinary');if(mode==='handler-api')throw c.error('FORBIDDEN',{message:'handler explicit'});if(mode==='raw')return Response.json({principal:current!.user.id,name:c.body.name});return c.json({principal:current!.user.id,name:c.body.name})}),disabled:createAuthEndpoint('/disabled',{method:'POST'},async c=>c.json({never:true}))},onResponse(r){if(activeMode)events.push({stage:'http-response-second',status:r.status})}
}]};
const originalEndpoint=authOptions.plugins[1].endpoints.write;
authOptions.plugins[1].endpoints.write=Object.assign(async (input:any)=>{const result=await originalEndpoint(input);return activeMode==='raw'?result.response:result}, originalEndpoint);
const auth=betterAuth(authOptions);
let activeMode='';await(await getMigrations(auth.options)).runMigrations();
const cookies:string[]=[];const ids:string[]=[];
for(const actor of ['a','b']){const response=await auth.handler(new Request('http://original.test/api/auth/sign-up/email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:`${actor}@composition.test`,password:'Password123!',name:actor})}));const body=await response.json();if(response.status!==200)throw new Error(JSON.stringify(body));cookies.push(response.headers.getSetCookie().find(c=>c.startsWith('better-auth.session_token='))!.split(';')[0]);ids.push(body.user.id)}cookieB=cookies[1];
for(const mode of ['context-request','replace','no-patch','handler-api','handler-ordinary','after-api','after-ordinary','response-replace','response-api','response-ordinary','request-api','request-ordinary','early','stop','raw','unknown','disabled']){events=[];activeMode=mode;const path=mode==='replace'||mode==='unknown'?'/absent':mode==='disabled'?'/disabled':'/write';const req=new Request('http://original.test/api/auth'+path,{method:'POST',headers:{'content-type':'application/json',origin:'http://original.test',cookie:mode==='replace'?cookies[0]:cookies[1],'x-mode':mode},body:JSON.stringify({name:'original-'+mode})});let result;try{const r=await auth.handler(req);result={status:r.status,headers:[...r.headers],body:await r.text()}}catch(e:any){result={rejected:true,status:e.statusCode??500,message:e.message}}console.log(JSON.stringify({backend:'source',mode,result,events,actors:ids,rows:db.query('SELECT email,name FROM user ORDER BY email').all(),physicalUsers:db.query('SELECT count(*) as n FROM user').get(),physicalSessions:db.query('SELECT count(*) as n FROM session').get(),physicalRows:{users:db.query('SELECT * FROM user ORDER BY rowid').all(),accounts:db.query('SELECT * FROM account ORDER BY rowid').all(),sessions:db.query('SELECT * FROM session ORDER BY rowid').all()}}))}
