import {betterAuth} from 'better-auth';
import {APIError,createAuthEndpoint,createAuthMiddleware} from 'better-auth/api';
import {Database} from 'bun:sqlite';
import {getMigrations} from 'better-auth/db/migration';
const db=new Database(':memory:'); const events:any[]=[];
const snapshot=(r:Request,c:any)=>({url:r.url,origin:c.baseURL,trusted:c.trustedOrigins,providers:c.trustedProviders});
const auth=betterAuth({database:db,secret:'close181-source-secret-minimum-32',baseURL:{allowedHosts:['original.test','replacement.test'],protocol:'http'},logger:{disabled:true},trustedOrigins:(r)=>{events.push(['origins',r?.url]);return [r?new URL(r.url).origin:'http://original.test']},account:{accountLinking:{trustedProviders:(r)=>{events.push(['providers',r?.url]);return [r?new URL(r.url).host:'original.test']}}},disabledPaths:['/disabled'],hooks:{before:createAuthMiddleware(async c=>{events.push(['global-before',c.path]); if(c.headers?.get('x-mode')==='stop') return c.json({stop:true}); return {context:{body:{name:'patched'}}}}),after:createAuthMiddleware(async c=>{events.push(['global-after',c.path]); c.setHeader('x-global','after');})},plugins:[{id:'replace',init(c){events.push(['init-first']); return {context:{marker:'first'}}},onRequest(r,c){events.push(['request-first',snapshot(r,c)]);const mode=r.headers.get('x-mode');if(mode==='request-ordinary')throw new Error('request-failure');if(mode==='request-api')throw new APIError('FORBIDDEN',{message:'request explicit'});if(mode==='early')return {response:Response.json({early:true})};if(mode==='replace'){const headers=new Headers(r.headers);headers.set('x-replaced','yes');return {request:new Request('http://replacement.test/api/auth/write',{method:'POST',headers,body:JSON.stringify({name:'original'})})}}},onResponse(r,c){events.push(['response-first',r.status,c.baseURL,r.headers.get('x-global')]);const mode=r.headers.get('x-mode'); if(mode==='response-ordinary')throw new Error('response-failure');if(mode==='response-api')throw new APIError('FORBIDDEN',{message:'response explicit'}); if(r.headers.get('x-replace-response'))return {response:new Response('replacement',{status:202,headers:{'x-replaced-response':'yes'}})} }},{id:'write',init(c){events.push(['init-second',c.marker]);return {context:{marker:'second'}}},onRequest(r,c){events.push(['request-second',snapshot(r,c)]);},endpoints:{write:createAuthEndpoint('/write',{method:'POST'},async c=>{events.push(['handler',c.body,c.context.marker,c.context.baseURL]);await c.context.internalAdapter.createUser({email:`${c.headers?.get('x-case')}@close181.test`,name:c.body?.name??'none',emailVerified:false});c.setHeader('x-mode',c.headers?.get('x-mode')??'');c.setHeader('x-replace-response',c.headers?.get('x-replace-response')??'');c.setCookie('issued','yes',{path:'/'});if(c.headers?.get('x-mode')==='handler-ordinary')throw new Error('handler-failure');if(c.headers?.get('x-mode')==='handler-api')throw c.error('FORBIDDEN',{message:'handler explicit'});return c.json({name:c.body?.name})})},onResponse(r){events.push(['response-second',r.status]);return {response:new Response(r.body,{status:r.status,headers:r.headers})}}}]});
await(await getMigrations(auth.options)).runMigrations(); await auth.$context; console.log(JSON.stringify({init:[...events]}));
for(const [i,mode,path] of [['1','replace','/absent'],['2','early','/write'],['3','stop','/write'],['4','handler-ordinary','/write'],['5','handler-api','/write'],['6','response-ordinary','/write'],['7','response-api','/write'],['8','request-ordinary','/write'],['9','request-api','/write'],['10','normal','/disabled'],['11','normal','/absent'],['12','normal','/write']]){events.length=0;let result;try{const r=await auth.handler(new Request('http://original.test/api/auth'+path,{method:'POST',headers:{'content-type':'application/json','x-mode':mode,'x-case':i,'x-replace-response':i==='12'?'yes':''},body:JSON.stringify({name:'original'})}));result={status:r.status,headers:[...r.headers],body:await r.text()}}catch(e:any){result={rejected:e.constructor.name,message:e.message,status:e.statusCode}}console.log(JSON.stringify({i,mode,result,events:[...events],rows:db.query('SELECT email,name FROM user ORDER BY email').all()}))}
