[package]
name = "alibi-cli"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
description = "Schema generator for Alibi authentication"
repository = { workspace = true }
homepage = { workspace = true }
documentation = "https://docs.rs/alibi-cli"
publish = ["crates-io"]
include = ["/src/**", "/migrations/**", "/README.md", "/LICENSE"]

readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "better-auth-rs"
path = "src/main.rs"

[dependencies]
better-auth-schema-registry = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
