[package]
name = "alibi-sqlx"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
description = "SQLx integration for Alibi"
repository = { workspace = true }
homepage = { workspace = true }
documentation = "https://docs.rs/alibi-sqlx"
publish = ["crates-io"]
include = ["/src/**", "/migrations/**", "/README.md", "/LICENSE"]

readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lib]
name = "alibi_sqlx"

[lints]
workspace = true

[dependencies]
alibi-core = { workspace = true }
alibi-sqlx-macros = { version = "0.4.0", path = "../sqlx-macros" }

async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ryu-js = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

sqlx = { version = "0.9", default-features = false, features = ["runtime-tokio", "chrono", "json", "uuid", "derive"] }

[features]
default = ["sqlite", "postgres"]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
tls-rustls = ["sqlx/tls-rustls"]
tls-native-tls = ["sqlx/tls-native-tls"]

[package.metadata.docs.rs]
all-features = true
