import {expect} from "bun:test";
import {compatScenario,type ScenarioContext} from "../../support/scenario";
import {authProfilePath,type FixtureProfile} from "../../support/profiles";

compatScenario("cloudflare mapped invalid subjects reach application mapper before denial", async ctx => {
  const foreign = ctx.actor("foreign");
  expect((await foreign.client.signUp.email({email:ctx.uniqueEmail("foreign"),password:"Password123!",name:"Foreign Owner"})).error).toBeNull();
  const before = await state(ctx);
  const originals: Record<string, unknown>[] = [];
  const callbacks: unknown[] = [];
  for (const variant of ["missing", "null", "empty"] as const) {
    const original: Record<string, unknown> = {...profile(ctx), applicationField:"Original profile receipt"};
    if (variant === "missing") delete original.id;
    else original.id = variant === "null" ? null : "";
    originals.push(original);
    await control(ctx, {profile:original});
    const flow = await callback(ctx, "social-cloudflare-mapped");
    const observed = await ctx.rawRequest({path:"/__test/cloudflare/mapper-receipts"});
    expect(observed.status).toBe(200);
    expect(observed.body).toEqual(originals);
    expect(flow.response.status).toBe(302);
    const error = new URL(flow.response.headers.get("location")!, ctx.baseURL).searchParams.get("error");
    expect(error).toBe("unable_to_get_user_info");
    expect(await state(ctx)).toEqual(before);
    expect((await flow.actor.client.getSession()).data).toBeNull();
    expect(await receipts(ctx)).toHaveLength(originals.length * 2);
    callbacks.push({status:flow.response.status,error});
  }
  const mapperReceipts = (await ctx.rawRequest({path:"/__test/cloudflare/mapper-receipts"})).body as Record<string,unknown>[];
  return {before,after:await state(ctx),callbacks,mapperReceipts:mapperReceipts.map(({id:rawSubject,...fields})=>({...fields,rawSubject}))};
}, ["GET /callback/{}"]);

async function state(ctx:ScenarioContext){const r=await ctx.rawRequest({path:"/__test/social-provider/state"});expect(r.status).toBe(200);return r.body as {users:Array<Record<string,unknown>>;accounts:Array<Record<string,unknown>>;sessions:Array<Record<string,unknown>>};}
async function control(ctx:ScenarioContext,value:Record<string,unknown>){expect((await ctx.rawRequest({path:"/__test/cloudflare/control",method:"POST",json:value})).status).toBe(200);}
async function receipts(ctx:ScenarioContext){const r=await ctx.rawRequest({path:"/__test/cloudflare/receipts"});expect(r.status).toBe(200);return (r.body as Array<{path:string;authorization:string|null;body:Record<string,string>|null}>).map(row=>({...row,body:(row.body?.code_verifier?{...row.body,code_verifier:{token:row.body.code_verifier,length:row.body.code_verifier.length}}:row.body) as Record<string,unknown>|null}));}
function profile(ctx:ScenarioContext){return {id:ctx.uniqueToken("cloudflare-subject"),first_name:"Cloudflare",last_name:"Name",email:ctx.uniqueEmail("cloudflare"),country:"Synthetic Country",two_factor_authentication_enabled:true};}
async function callback(ctx:ScenarioContext,mode:FixtureProfile="social-cloudflare-default",requestSignUp=false){const actor=ctx.actor("cloudflare",mode);const start=await actor.client.signIn.social({provider:"cloudflare",callbackURL:"/dashboard",requestSignUp});expect(start.error).toBeNull();const url=new URL(start.data!.url!);const path=authProfilePath(mode)+`/callback/cloudflare?code=fixture-code&state=${encodeURIComponent(url.searchParams.get("state")!)}`;const response=await actor.fetch(ctx.baseURL+path,{redirect:"manual"});return {actor,start,url,path,response};}

for(const mode of ["default","configured","disabled-scope","disabled-configured","configured-endpoint"] as const)compatScenario(`cloudflare published ${mode} authorization deduplicates scopes and uses PKCE`,async ctx=>{
 const result=await ctx.actor("cloudflare",`social-cloudflare-${mode}`).client.signIn.social({provider:"cloudflare",callbackURL:"/dashboard",scopes:["requested-scope","user-details.read","requested-scope"],loginHint:"ignored@example.invalid"});expect(result.error).toBeNull();const url=new URL(result.data!.url!);expect(url.origin).toBe(mode==="configured-endpoint"?"https://configured.example.invalid":"https://dash.cloudflare.com");expect(url.pathname).toBe(mode==="configured-endpoint"?"/authorize":"/oauth2/auth");expect(url.searchParams.get("response_type")).toBe("code");expect(url.searchParams.get("response_mode")).toBeNull();expect(url.searchParams.get("login_hint")).toBeNull();expect(url.searchParams.get("prompt")).toBeNull();expect(url.searchParams.get("code_challenge_method")).toBe("S256");expect(url.searchParams.get("code_challenge")).toBeTruthy();expect(url.searchParams.get("scope")).toBe(mode==="disabled-configured"?"configured-scope user-details.read requested-scope":mode==="disabled-scope"?"requested-scope user-details.read":mode==="configured"?"user-details.read configured-scope requested-scope":"user-details.read requested-scope");expect(url.searchParams.get("redirect_uri")).toBe(mode==="configured-endpoint"?"https://configured.example.invalid/callback":ctx.baseURL+authProfilePath(`social-cloudflare-${mode}`)+"/callback/cloudflare");return {result:ctx.snapshot(result),persisted:await state(ctx),receipts:await receipts(ctx)};
});
compatScenario("cloudflare disabled defaults with no requested scopes omits scope",async ctx=>{const result=await ctx.actor("cloudflare","social-cloudflare-disabled-scope").client.signIn.social({provider:"cloudflare"});expect(result.error).toBeNull();expect(new URL(result.data!.url!).searchParams.get("scope")).toBeNull();return {result:ctx.snapshot(result)};});

for(const mode of ["default","public","post","encoded","configured-endpoint"] as const)compatScenario(`cloudflare ${mode} credentials reach real token exchange refresh and owned persistence`,async ctx=>{
 const foreign=ctx.actor("foreign");expect((await foreign.client.signUp.email({email:ctx.uniqueEmail("foreign"),password:"Password123!",name:"Foreign Owner"})).error).toBeNull();const before=await state(ctx);const data=profile(ctx);await control(ctx,{profile:data});const fixtureMode=`social-cloudflare-${mode}` as const;const flow=await callback(ctx,fixtureMode);expect(flow.response.status).toBe(302);expect(flow.response.headers.get("location")).toBe("/dashboard");const session=await flow.actor.client.getSession();expect(session.data?.user).toBeTruthy();const after=await state(ctx);for(const table of ["users","accounts","sessions"] as const){expect(after[table]).toHaveLength(before[table].length+1);expect(after[table].find(row=>row.id===before[table][0]!.id)).toEqual(before[table][0]);}const owner=after.users.find(row=>row.id!==before.users[0]!.id)!;expect(owner).toMatchObject({name:"Cloudflare Name",email:data.email,emailVerified:false,image:null});const account=after.accounts.find(row=>row.userId===owner.id)!;expect(account).toMatchObject({providerId:"cloudflare",accountId:data.id,accessToken:"fixture-cloudflare-access",refreshToken:"fixture-cloudflare-refresh",idToken:null,scope:"user-details.read"});
 const raw=await ctx.rawRequest({path:"/__test/cloudflare/receipts"});const rows=raw.body as Array<{path:string;authorization:string|null;body:Record<string,string>}>;const exchange=rows[0]!.body;const verifier=exchange.code_verifier!;expect(verifier).toHaveLength(128);expect(flow.url.searchParams.get("code_challenge")).toBe(Buffer.from(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier))).toString("base64url"));const credentials:Record<string,string>=mode==="public"?{client_id:"fixture-social-client"}:mode==="post"?{client_id:"fixture-social-client",client_secret:"fixture-social-secret"}:{};expect(exchange).toEqual({grant_type:"authorization_code",code:"fixture-code",code_verifier:verifier,redirect_uri:mode==="configured-endpoint"?"https://configured.example.invalid/callback":ctx.baseURL+authProfilePath(fixtureMode)+"/callback/cloudflare",...credentials});const authorization=mode==="public"||mode==="post"?null:mode==="encoded"?"Basic Y2xpZW50KyUzQSUyQiUyMSolMjclMjglMjk6c2VjcmV0KyUzQSUyQiUyMSolMjclMjglMjk=":"Basic Zml4dHVyZS1zb2NpYWwtY2xpZW50OmZpeHR1cmUtc29jaWFsLXNlY3JldA==";expect(rows[0]!.authorization).toBe(authorization);expect(rows[1]).toMatchObject({path:"/user",authorization:"Bearer fixture-cloudflare-access",body:null});
 const replay=await flow.actor.fetch(ctx.baseURL+flow.path,{redirect:"manual"});expect(replay.status).toBe(302);expect(await state(ctx)).toEqual(after);expect(await receipts(ctx)).toHaveLength(2);
 const denied=await foreign.client.refreshToken({accountId:String(account.id)});expect(denied.error).toBeTruthy();expect(await state(ctx)).toEqual(after);expect(await receipts(ctx)).toHaveLength(2);await control(ctx,{tokenResponse:{access_token:"rotated-cloudflare-access",refresh_token:"rotated-cloudflare-refresh",token_type:"Bearer",expires_in:1800,scope:"user-details.read updated"}});const refreshed=await flow.actor.client.refreshToken({accountId:String(account.id)});expect(refreshed.error).toBeNull();const rotated=await state(ctx);expect(rotated.accounts.find(row=>row.id===account.id)).toMatchObject({accessToken:"rotated-cloudflare-access",refreshToken:"rotated-cloudflare-refresh",scope:"user-details.read"});expect(rotated.users).toEqual(after.users);expect(rotated.sessions).toEqual(after.sessions);expect(rotated.accounts.find(row=>row.id===before.accounts[0]!.id)).toEqual(before.accounts[0]);const refreshRequests=await receipts(ctx);expect(refreshRequests[2]).toMatchObject({path:"/token",authorization,body:{grant_type:"refresh_token",refresh_token:"fixture-cloudflare-refresh",...credentials}});expect((await flow.actor.client.signOut()).error).toBeNull();const logout=await state(ctx);expect(logout.users).toEqual(rotated.users);expect(logout.accounts).toEqual(rotated.accounts);expect(logout.sessions).toEqual(before.sessions);expect(await receipts(ctx)).toEqual(refreshRequests);return {start:ctx.snapshot(flow.start),callback:{status:flow.response.status,location:flow.response.headers.get("location")},session:ctx.snapshot(session),before,after,replay:{status:replay.status,location:replay.headers.get("location")},denied:ctx.snapshot(denied),refreshed:ctx.snapshot(refreshed),rotated,logout,receipts:refreshRequests};
},["POST /sign-in/social", "GET /callback/{}", "POST /refresh-token", "POST /sign-out"]);

for(const variant of ["first-only","last-only","missing-names","null-names","empty-names","numeric-name","zero-name","numeric-subject","mapped"] as const)compatScenario(`cloudflare actual API ${variant} mapping retains independent raw subject`,async ctx=>{
 const data:Record<string,unknown>=profile(ctx);if(variant==="first-only")delete data.last_name;if(variant==="last-only")delete data.first_name;if(variant==="missing-names"){delete data.first_name;delete data.last_name;}if(variant==="null-names"){data.first_name=null;data.last_name=null;}if(variant==="empty-names"){data.first_name="";data.last_name="";}if(variant==="numeric-name"){data.first_name=7;data.last_name=42;}if(variant==="zero-name"){data.first_name=0;data.last_name="";}if(variant==="numeric-subject")data.id=42;await control(ctx,{profile:data});const flow=await callback(ctx,variant==="mapped"?"social-cloudflare-mapped":"social-cloudflare-default");expect(flow.response.headers.get("location")).toBe("/dashboard");const persisted=await state(ctx);expect(persisted.users).toHaveLength(1);expect(persisted.accounts).toHaveLength(1);expect(persisted.sessions).toHaveLength(1);expect(persisted.users[0]).toMatchObject({name:variant==="mapped"?"Mapped Cloudflare":variant==="first-only"?"Cloudflare":variant==="last-only"?"Name":variant==="numeric-name"?"7 42":["missing-names","null-names","empty-names","zero-name"].includes(variant)?data.email:"Cloudflare Name",email:variant==="mapped"?"mapped-cloudflare@example.invalid":data.email,emailVerified:variant==="mapped",image:variant==="mapped"?"https://images.example.invalid/mapped-cloudflare.png":null});expect(persisted.accounts[0]!.accountId).toBe(String(data.id));const session=await flow.actor.client.getSession();expect(session.data?.user).toBeTruthy();return {start:ctx.snapshot(flow.start),callback:{status:flow.response.status,location:flow.response.headers.get("location")},session:ctx.snapshot(session),persisted,receipts:await receipts(ctx)};
},["POST /sign-in/social", "GET /callback/{}"]);

for(const variant of ["missing-subject","null-subject","empty-subject","missing-email","null-email","empty-email","api-denied","api-no-result","api-null-result","userinfo-status","token-status","token-redirect","implicit-disabled","signup-disabled"] as const)compatScenario(`cloudflare rejects ${variant} without foreign writes`,async ctx=>{
 const foreign=ctx.actor("foreign");expect((await foreign.client.signUp.email({email:ctx.uniqueEmail("foreign"),password:"Password123!",name:"Foreign Owner"})).error).toBeNull();const before=await state(ctx);const data:Record<string,unknown>=profile(ctx);if(variant==="missing-subject")delete data.id;if(variant==="null-subject")data.id=null;if(variant==="empty-subject")data.id="";if(variant==="missing-email")delete data.email;if(variant==="null-email")data.email=null;if(variant==="empty-email")data.email="";await control(ctx,{profile:data,...(variant==="api-denied"?{envelope:{success:false,result:data,errors:[{code:1000,message:"Synthetic provider error"}]}}:{}),...(variant==="api-no-result"?{envelope:{success:true}}:{}),...(variant==="api-null-result"?{envelope:{success:true,result:null}}:{}),...(variant==="userinfo-status"?{profileStatus:500}:{}),...(variant==="token-status"?{tokenStatus:400}:{}),...(variant==="token-redirect"?{tokenStatus:307,tokenRedirect:true}:{})});const flow=await callback(ctx,variant==="implicit-disabled"?"social-cloudflare-implicit-disabled":variant==="signup-disabled"?"social-cloudflare-signup-disabled":"social-cloudflare-default");expect(flow.response.status).toBe(302);expect(new URL(flow.response.headers.get("location")!,ctx.baseURL).searchParams.get("error")).toBe(variant.endsWith("email")?"email_not_found":variant.startsWith("token-")?"invalid_code":variant.endsWith("disabled")?"signup_disabled":"unable_to_get_user_info");const after=await state(ctx);expect(after).toEqual(before);if(variant==="token-redirect")expect(await receipts(ctx)).toHaveLength(1);expect((await flow.actor.client.getSession()).data).toBeNull();return {start:ctx.snapshot(flow.start),callback:{status:flow.response.status,location:flow.response.headers.get("location")},before,after,receipts:await receipts(ctx)};
},["GET /callback/{}"]);
compatScenario("cloudflare explicit signup admits disabled implicit signup",async ctx=>{await control(ctx,{profile:profile(ctx)});const flow=await callback(ctx,"social-cloudflare-implicit-disabled",true);expect(flow.response.headers.get("location")).toBe("/dashboard");const persisted=await state(ctx);expect(persisted.users).toHaveLength(1);expect(persisted.accounts).toHaveLength(1);expect(persisted.sessions).toHaveLength(1);return {start:ctx.snapshot(flow.start),callback:{status:flow.response.status,location:flow.response.headers.get("location")},persisted,receipts:await receipts(ctx)};},["POST /sign-in/social", "GET /callback/{}"]);
compatScenario("cloudflare unverified email gate stores account without issuing session",async ctx=>{await control(ctx,{profile:profile(ctx)});const flow=await callback(ctx,"social-cloudflare-required");expect(new URL(flow.response.headers.get("location")!,ctx.baseURL).searchParams.get("error")).toBe("email_not_verified");const persisted=await state(ctx);expect(persisted.users).toHaveLength(1);expect(persisted.users[0]!.emailVerified).toBeFalse();expect(persisted.accounts).toHaveLength(1);expect(persisted.sessions).toHaveLength(0);expect((await flow.actor.client.getSession()).data).toBeNull();return {callback:{status:flow.response.status,location:flow.response.headers.get("location")},persisted,receipts:await receipts(ctx)};},["POST /sign-in/social", "GET /callback/{}"]);
for(const expiry of ["absent","zero","fractional"] as const)compatScenario(`cloudflare ${expiry} token expiry has no fabricated default`,async ctx=>{const started=Date.now();const tokenResponse={access_token:"fixture-cloudflare-access",refresh_token:"fixture-cloudflare-refresh",token_type:"Bearer",scope:"user-details.read",...(expiry==="absent"?{}:{expires_in:expiry==="zero"?0:120.5})};await control(ctx,{profile:profile(ctx),tokenResponse});const flow=await callback(ctx);expect(flow.response.headers.get("location")).toBe("/dashboard");const persisted=await state(ctx);const expires=persisted.accounts[0]!.accessTokenExpiresAt;if(expiry==="fractional"){expect(typeof expires).toBe("string");expect(Date.parse(String(expires))).toBeGreaterThanOrEqual(started+120500);expect(Date.parse(String(expires))).toBeLessThanOrEqual(Date.now()+120500);}else expect(expires).toBeNull();return {persisted,receipts:await receipts(ctx)};},["POST /sign-in/social", "GET /callback/{}"]);
compatScenario("cloudflare unsupported ID token and invalid provider state produce no requests",async ctx=>{const before=await state(ctx);const actor=ctx.actor("cloudflare","social-cloudflare-default");const direct=await actor.client.signIn.social({provider:"cloudflare",idToken:{token:"untrusted.not-signed.token"}});expect(direct.error?.code).toBe("ID_TOKEN_NOT_SUPPORTED");const wrong=await actor.client.signIn.social({provider:"google"});expect(wrong.error?.code).toBe("PROVIDER_NOT_FOUND");const response=await actor.fetch(ctx.baseURL+authProfilePath("social-cloudflare-default")+"/callback/cloudflare?code=fixture-code&state=unissued",{redirect:"manual"});expect(response.status).toBe(302);expect(new URL(response.headers.get("location")!,ctx.baseURL).searchParams.get("error")).toBe("state_mismatch");expect(await state(ctx)).toEqual(before);expect(await receipts(ctx)).toEqual([]);return {direct:ctx.snapshot(direct),wrong:ctx.snapshot(wrong),persisted:await state(ctx),receipts:await receipts(ctx)};},["POST /sign-in/social", "GET /callback/{}"]);
