[package]
name = "alibi-sqlx-macros"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
description = "SQLx proc macros for Alibi"
repository = { workspace = true }
homepage = { workspace = true }
documentation = "https://docs.rs/alibi-sqlx-macros"
publish = ["crates-io"]
include = ["/src/**", "/migrations/**", "/README.md", "/LICENSE"]

readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[lib]
name = "better_auth_sqlx_macros"
proc-macro = true

[dependencies]
better-auth-entity-codegen = { workspace = true }
proc-macro-crate = "3"
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[package.metadata.docs.rs]
all-features = true
