[package]
name = "better-auth-seaorm"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = "SeaORM integration for better-auth"
repository = { workspace = true }

readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[dependencies]
better-auth-core = { workspace = true }
better-auth-seaorm-macros = { version = "1.0.0-alpha.3", path = "../seaorm-macros" }

async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ryu-js = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

sea-orm = { version = "2.0.4", features = ["runtime-tokio", "sqlx-postgres", "sqlx-sqlite", "macros", "with-chrono", "with-json", "with-uuid"] }
sea-orm-migration = { version = "2.0.4", features = ["runtime-tokio", "sqlx-postgres", "sqlx-sqlite"] }

[features]
tls-rustls = ["sea-orm/runtime-tokio-rustls", "sea-orm-migration/runtime-tokio-rustls"]
tls-native-tls = ["sea-orm/runtime-tokio-native-tls", "sea-orm-migration/runtime-tokio-native-tls"]
