[package]
name = "alibi-seaorm"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
description = "SeaORM integration for Alibi"
repository = { workspace = true }
homepage = { workspace = true }
documentation = "https://docs.rs/alibi-seaorm"
publish = ["crates-io"]
include = ["/src/**", "/migrations/**", "/README.md", "/LICENSE"]

readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lib]
name = "alibi_seaorm"

[lints]
workspace = true

[dependencies]
alibi-core = { workspace = true }
alibi-seaorm-macros = { version = "0.3.0", path = "../seaorm-macros" }

async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ryu-js = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

sea-orm = { version = "2.0.4", features = ["runtime-tokio", "sqlx-postgres", "sqlx-sqlite", "macros", "with-chrono", "with-json", "with-uuid"] }
sea-orm-migration = { version = "2.0.4", features = ["runtime-tokio", "sqlx-postgres", "sqlx-sqlite"] }

[features]
tls-rustls = ["sea-orm/runtime-tokio-rustls", "sea-orm-migration/runtime-tokio-rustls"]
tls-native-tls = ["sea-orm/runtime-tokio-native-tls", "sea-orm-migration/runtime-tokio-native-tls"]

[package.metadata.docs.rs]
all-features = true
