import {expect} from "bun:test";
import {z} from "zod";
import {compatScenario} from "../../support/scenario";
const dates={createdAt:"2026-10-01T00:00:00.016562+00:00",updatedAt:"2026-10-01T00:01:00.489730Z",lastRequest:"2026-10-01T00:02:00.290730Z",lastRefillAt:"2026-10-01T05:33:00.123456+05:30",expiresAt:"2099-10-01T00:04:00.456789+00:00"};
const expected={createdAt:"2026-10-01T00:00:00.016Z",updatedAt:"2026-10-01T00:01:00.489Z",lastRequest:"2026-10-01T00:02:00.290Z",lastRefillAt:"2026-10-01T00:03:00.123Z",expiresAt:"2099-10-01T00:04:00.456Z"};
const row=z.object({id:z.string()}).passthrough();
compatScenario("api-key wire dates preserve actual stored submillisecond instants through the published SDK and virtual sessions",async ctx=>{
 for(const action of ["reset","restore"]){expect((await ctx.rawRequest({path:"/__test/api-key-background/control",method:"POST",json:{action}})).status).toBe(200);}
 const owner=ctx.actor("timestamp-owner","api-key-automatic"),foreign=ctx.actor("timestamp-foreign","api-key-automatic");
 for(const [actor,name]of [[owner,"timestamp-owner"],[foreign,"timestamp-foreign"]]as const){expect((await actor.client.signUp.email({name,email:ctx.uniqueEmail(name),password:"password123"})).error).toBeNull();}
 const cleanup=await ctx.rawRequest({path:"/__test/api-key-background/cleanup?profile=api-key-automatic",method:"POST"});expect(cleanup.status).toBe(200);expect(cleanup.body).toEqual({success:true,error:null});
 const created=await owner.client.$fetch("/api-key/create",{method:"POST",body:{name:"timestamp-owned"}}),foreignCreated=await foreign.client.$fetch("/api-key/create",{method:"POST",body:{name:"timestamp-foreign"}});expect(created.error).toBeNull();expect(foreignCreated.error).toBeNull();
 const key=z.object({id:z.string(),key:z.string()}).passthrough().parse(ctx.snapshot(created.data));
 const stored=async()=>{const result=await ctx.rawRequest({path:"/__test/api-key-background/state?rawDates=true"});expect(result.status).toBe(200);return z.array(row).parse(result.body);};
 const before=await stored(),foreignBefore=before.find(value=>value.id===row.parse(foreignCreated.data).id);
 const staged=await ctx.rawRequest({path:"/__test/api-key-background/control",method:"POST",json:{action:"timestamps",keyId:key.id,dates}});expect(staged.status).toBe(200);
 const physical=await stored();expect(physical.find(value=>value.id===key.id)).toEqual({...row.parse(before.find(value=>value.id===key.id)),...dates});expect(physical.find(value=>value.id===foreignBefore?.id)).toEqual(foreignBefore);
 const projected=await ctx.rawRequest({path:"/__test/api-key-background/state"});expect(projected.status).toBe(200);expect(z.array(row).parse(projected.body).find(value=>value.id===key.id)).toEqual({...row.parse(physical.find(value=>value.id===key.id)),...expected});
 const get=await owner.client.$fetch("/api-key/get",{query:{id:key.id}});expect(get.error).toBeNull();expect(ctx.snapshot(get.data)).toMatchObject(expected);for(const field of Object.keys(dates)){expect((get.data as Record<string,unknown>)[field]).toBeInstanceOf(Date);}
 const raw=await owner.fetch(`/__test/profiles/api-key-automatic/api/auth/api-key/get?id=${key.id}`);expect(raw.status).toBe(200);const rawBody=await raw.json();expect(rawBody).toMatchObject(expected);expect(rawBody).toEqual(row.parse(ctx.snapshot(get.data)));
 const list=await owner.client.$fetch("/api-key/list");expect(list.error).toBeNull();const listed=z.object({apiKeys:z.array(row)}).parse(ctx.snapshot(list.data));expect(listed.apiKeys.find(value=>value.id===key.id)).toEqual(row.parse(ctx.snapshot(get.data)));
 const denied=await foreign.client.$fetch("/api-key/get",{query:{id:key.id}});expect(denied.error).toMatchObject({status:404,code:"KEY_NOT_FOUND"});expect(await stored()).toEqual(physical);
 const verified=await ctx.rawRequest({path:"/__test/api-key-background/verify?profile=api-key-automatic",method:"POST",json:{key:key.key}});expect(verified.status).toBe(200);const verification=z.object({valid:z.literal(true),error:z.null(),key:row}).parse(verified.body);expect(verification.key).toMatchObject({createdAt:expected.createdAt,lastRefillAt:expected.lastRefillAt,expiresAt:expected.expiresAt});
 const started=Date.now(),session=await owner.client.getSession({fetchOptions:{headers:{"x-api-key":key.key}}}),finished=Date.now();expect(session.error).toBeNull();const sessionBody=z.object({session:z.record(z.string(),z.unknown()),user:row}).parse(ctx.snapshot(session.data));expect(sessionBody.session.expiresAt).toBe(expected.expiresAt);for(const field of ["createdAt","updatedAt"]){const value=(session.data as {session:Record<string,unknown>}).session[field];expect(value).toBeInstanceOf(Date);expect((value as Date).getTime()).toBeGreaterThanOrEqual(started-1000);expect((value as Date).getTime()).toBeLessThanOrEqual(finished+1000);}
 const rawSession=await owner.fetch("/__test/profiles/api-key-automatic/api/auth/get-session",{headers:{"x-api-key":key.key}});expect(rawSession.status).toBe(200);const rawSessionBody=await rawSession.json();expect(Object.keys(rawSessionBody.session).sort()).toEqual(["id","token","userId","userAgent","ipAddress","createdAt","updatedAt","expiresAt"].sort());for(const field of ["createdAt","updatedAt","expiresAt"]){expect(rawSessionBody.session[field]).toMatch(/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/);}expect(rawSessionBody.session.expiresAt).toBe(expected.expiresAt);
 const after=await stored();expect(after.find(value=>value.id===foreignBefore?.id)).toEqual(foreignBefore);const retained=after.find(value=>value.id===key.id);expect(retained).toMatchObject({createdAt:dates.createdAt,lastRefillAt:dates.lastRefillAt,expiresAt:dates.expiresAt});
 return {cleanup,created:ctx.snapshot(created),foreignCreated:ctx.snapshot(foreignCreated),before,physical,projected,get:ctx.snapshot(get),rawBody,list:ctx.snapshot(list),denied:ctx.snapshot(denied),verified,session:ctx.snapshot(session),rawSessionBody,after};
},["GET /api-key/get","GET /api-key/list","GET /get-session"]);
