import type { Database } from "bun:sqlite";
import { betterAuth, type BetterAuthOptions, type BetterAuthPlugin } from "better-auth";
import { APIError, createAuthMiddleware } from "better-auth/api";
import { emailOTP, jwt, oneTimeToken, organization, twoFactor } from "better-auth/plugins";
import { apiKey } from "@better-auth/api-key";
import { kAPIErrorHeaderSymbol } from "better-call";
import { getCurrentAuthEndpointContext } from "@better-auth/core/context";

type Context = { path?: unknown; method?: unknown; body?: unknown; query?: unknown; headers?: Headers; request?: Request; context: { session?: unknown; returned?: unknown } };
function inputSnapshot(ctx: Context) {
  return {
    pathPresent: Object.hasOwn(ctx,"path"), path: ctx.path ?? null,
    methodPresent: Object.hasOwn(ctx,"method"), method: ctx.method ?? null,
    bodyPresent: Object.hasOwn(ctx,"body"), body: ctx.body ?? null,
    queryPresent: Object.hasOwn(ctx,"query"), query: ctx.query ?? null,
    headers: ctx.headers ? Object.fromEntries(ctx.headers) : null,
    request: ctx.request ? {url:ctx.request.url,method:ctx.request.method,headers:Object.fromEntries(ctx.request.headers)} : null,
    session: ctx.context.session ?? null,
  };
}
function snapshot(ctx: Context) {
  const returned = ctx.context.returned;
  const current = getCurrentAuthEndpointContext() as unknown as Context;
  return {
    ...inputSnapshot(ctx),
    current: inputSnapshot(current),
    legacyRequest: current.request ? {url:current.request.url,method:current.request.method,headers:Object.fromEntries(current.request.headers)} : null,
    // API errors can originate from the separate better-call class. Capture
    // the real public typed error contract without relying on class identity.
    returned: returned instanceof Error && "statusCode" in returned && "body" in returned ? {api:true,status:returned.statusCode,body:returned.body} : returned ?? null,
  };
}

/** Actual application callbacks; receipts are generated by the installed runtime. */
export function createServerEndpointFixture(database: Database, base: BetterAuthOptions) {
  const path="/__test/profiles/server-dispatch/api/auth";
  let mode="normal", serial=0;
  const events: unknown[]=[];
  const other=betterAuth({...base,basePath:"/__test/server-dispatch/other/api/auth",plugins:[]});
  function observer(id:string): BetterAuthPlugin {
    return {id:`server-dispatch-${id}`,hooks:{
      before:[{matcher(ctx){events.push({stage:`${id}-matcher`,...snapshot(ctx)});if(id==="first"&&mode==="matcher-error")throw new Error("private matcher");return true;},handler:createAuthMiddleware(async ctx=>{
        events.push({stage:`${id}-before`,...snapshot(ctx)});
        if(mode==="before-headers")ctx.setHeader(`x-${id}`,"before");
        if(id==="first"&&mode==="cancel"){ctx.setHeader("x-before","cancel");return {cancelled:true,body:ctx.body};}
        if(id==="first"&&mode==="before-error")throw new Error("private before");
        if(id==="first"&&mode==="before-api")throw new APIError("FORBIDDEN",{code:"APP_BEFORE",message:"before denied"});
        if(mode==="patch"||mode==="patch-existing-headers")return {context:{body:id==="first"?{email:"FirstPatch@Example.test",nested:{first:true},actions:["first"]}:{type:"sign-in",nested:{second:true},actions:["second"],email:null},headers:new Headers({[`x-${id}`]:"patched"})}};
      })}],
      after:[{matcher:()=>true,handler:createAuthMiddleware(async ctx=>{
        events.push({stage:`${id}-after`,...snapshot(ctx)});
        if(id==="second"&&mode==="scope-isolation"){events.push({stage:"other-context-session",session:await other.api.getSession({headers:ctx.headers})});}
        if(id==="first"&&mode==="after-api"){ctx.setHeader("x-after","api-error");throw new APIError("FORBIDDEN",{code:"APP_AFTER",message:"after denied"});}
        if(id==="first"&&mode==="after-error")throw new Error("private after");
        if(id==="first"&&mode==="after-value"){ctx.setHeader("x-after","replacement");return {replacement:true,original:ctx.context.returned};}
      })}],
    }};
  }
  const auth=betterAuth({...base,basePath:path,
    hooks:{before:createAuthMiddleware(async ctx=>{events.push({stage:"user-before",...snapshot(ctx)});if(mode==="reset-app")serial=0;if(mode==="before-headers")ctx.setHeader("x-user","before");if(mode==="request-patch"&&ctx.request){const headers=new Headers(ctx.request.headers);headers.set("x-physical-patch","actual-clone");return {context:{request:new Request(ctx.request,{headers})}};}if(mode==="patch"||mode==="patch-existing-headers")return {context:{body:{email:"UserPatch@Example.test",nested:{user:true},actions:["user"]},headers:new Headers({"x-user":"patched"})}};}),after:createAuthMiddleware(async ctx=>{events.push({stage:"user-after",...snapshot(ctx)});})},
    plugins:[observer("first"),emailOTP({sendVerificationOTP:async()=>{},generateOTP(input,ctx){events.push({stage:"otp-generator",input,...snapshot(ctx)});return "591307";}}),apiKey({configId:"dispatch",enableSessionForAPIKeys:true,rateLimit:{enabled:false},defaultKeyLength:16,enableMetadata:true,customAPIKeyGetter(ctx){events.push({stage:"api-key-getter",...snapshot(ctx)});return ctx.headers?.get("x-api-key")??null;},customAPIKeyValidator({ctx,key}){events.push({stage:"api-key-validator",key,...snapshot(ctx)});return true;},customKeyGenerator(input){events.push({stage:"api-key-generator",input:{length:input.length,prefix:input.prefix??null}});return `server-dispatch-actual-key-${String(++serial).padStart(6,"0")}`;}}),observer("second"),oneTimeToken(),jwt(),organization(),twoFactor({backupCodeOptions:{customBackupCodesGenerate:()=>["application-backup-one","application-backup-two"]}})],
  });
  return {path,auth,async control(request:Request):Promise<Response|null>{
    const url=new URL(request.url);
    if(url.pathname==="/__test/server-dispatch/state")return Response.json({verification:database.query("SELECT * FROM verification ORDER BY identifier,id").all(),apikey:database.query("SELECT *,hex(CAST(start AS BLOB)) AS startHex,typeof(start) AS startType FROM apikey ORDER BY name,id").all().map(row=>({...row as Record<string,unknown>,enabled:!!(row as Record<string,unknown>).enabled,rateLimitEnabled:!!(row as Record<string,unknown>).rateLimitEnabled})),organization:database.query("SELECT * FROM organization ORDER BY slug,id").all(),member:database.query('SELECT * FROM member ORDER BY role,id').all(),session:database.query('SELECT id,"expiresAt",token,"createdAt","updatedAt","ipAddress","userAgent","userId","impersonatedBy","activeOrganizationId","activeTeamId" FROM session ORDER BY "createdAt",id').all()});
    if(url.pathname!=="/__test/server-dispatch/call"||request.method!=="POST")return null;
    const physicalRequest=request.clone();
    const input=await request.json() as {operation:string;mode?:string;body?:unknown;query?:unknown;headers?:Record<string,string>;physicalRequest?:boolean};
    mode=input.mode??"normal";events.length=0;
    const api=auth.api as unknown as Record<string,(args:Record<string,unknown>)=>Promise<unknown>>;
    const endpoint=api[input.operation];
    if(!endpoint)return Response.json({message:"unknown installed operation"},{status:400});
    const args:Record<string,unknown>={returnHeaders:true,returnStatus:true,asResponse:false};
    if(Object.hasOwn(input,"body"))args.body=input.body;
    if(Object.hasOwn(input,"query"))args.query=input.query;
    if(Object.hasOwn(input,"headers"))args.headers=new Headers(input.headers);
    if(input.physicalRequest)args.request=physicalRequest;
    let result:unknown;
    try{const value=await endpoint(args) as {response:unknown;headers:Headers;status?:number};result={ok:true,value:{headers:Object.fromEntries(value.headers),response:value.response,...(Object.hasOwn(value,"status")?{status:value.status}: {})}};}
    catch(error){const failure=error as Error&{statusCode?:number;body?:unknown;[kAPIErrorHeaderSymbol]?:Headers};const headers=failure[kAPIErrorHeaderSymbol];result={ok:false,name:failure.name,status:failure.statusCode??null,body:failure.body??null,message:failure.message,headers:headers?Object.fromEntries(headers):null};}
    return Response.json({events:[...events],result});
  }};
}
